# Generated by Django 3.1.1 on 2020-09-25 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crime_details',
            fields=[
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('estimated_date', models.IntegerField(default=None)),
                ('nature', models.CharField(default=None, max_length=30)),
                ('autopsia', models.CharField(default=None, max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Mercenaries',
            fields=[
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default=None, max_length=30)),
                ('last_name', models.CharField(default=None, max_length=30)),
                ('age', models.IntegerField(default=None)),
                ('gender', models.CharField(default=None, max_length=10)),
                ('cost', models.IntegerField(default=None)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=30)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default=None, max_length=30)),
                ('last_name', models.CharField(default=None, max_length=30)),
                ('autopsia', models.CharField(default=None, max_length=100)),
                ('gender', models.CharField(default=None, max_length=10)),
                ('age', models.IntegerField(default=None)),
                ('ethnic_group', models.CharField(default=None, max_length=20)),
                ('height', models.IntegerField(default=None)),
                ('hair_color', models.CharField(default=None, max_length=15)),
                ('eye_color', models.CharField(default=None, max_length=15)),
                ('profession', models.CharField(default=None, max_length=30)),
                ('resident', models.CharField(default=None, max_length=30)),
                ('income', models.IntegerField(default=None)),
                ('insurance_owner', models.BooleanField(default=None)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default=None, max_length=30)),
                ('last_name', models.CharField(default=None, max_length=30)),
                ('gender', models.CharField(default=None, max_length=10)),
                ('age', models.IntegerField(default=None)),
                ('ethnic_group', models.CharField(default=None, max_length=15)),
                ('height', models.IntegerField(default=None)),
                ('hair_color', models.CharField(default=None, max_length=15)),
                ('eye_color', models.CharField(default=None, max_length=15)),
                ('phone_number', models.IntegerField(default=None)),
                ('email', models.CharField(default=None, max_length=50)),
                ('profession', models.CharField(default=None, max_length=30)),
                ('resident', models.CharField(default=None, max_length=30)),
                ('income', models.IntegerField(default=None)),
                ('danger_level', models.BooleanField(default=None)),
                ('corruption_cost', models.IntegerField(default=None)),
                ('clothes_size', models.CharField(default=None, max_length=5)),
                ('bound_with_victim', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.victim')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('antecedent', models.CharField(default=None, max_length=100)),
                ('suspect_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.suspect')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Prisoners',
            fields=[
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('prime_value', models.IntegerField(default=None)),
                ('prisoner_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.suspect')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Killed',
            fields=[
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('prime_value', models.IntegerField(default=None)),
                ('murdered_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.suspect')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('value', models.IntegerField(default=None)),
                ('victim_insurance', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.victim')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Detective',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('cover', models.CharField(default=None, max_length=30)),
                ('money', models.IntegerField(default=3000)),
                ('number_of_mercenaries', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.mercenaries')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Crime_location',
            fields=[
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('location', models.CharField(default=None, max_length=100)),
                ('crime', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.crime_details')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='crime_details',
            name='crime_quest',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.quest'),
        ),
        migrations.AddField(
            model_name='crime_details',
            name='victim_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.victim'),
        ),
        migrations.CreateModel(
            name='Clues',
            fields=[
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('clue', models.CharField(default=None, max_length=200)),
                ('crime_clues', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.crime_details')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
