# Generated by Django 3.1.1 on 2020-09-19 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crime_detail',
            fields=[
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('estimated_date', models.IntegerField(default=None)),
                ('nature', models.CharField(default=None, max_length=30)),
                ('weapon_used', models.CharField(default=None, max_length=30)),
                ('autopsia', models.CharField(default=None, max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('Question1', models.CharField(default=None, max_length=500)),
                ('Response1', models.CharField(default=None, max_length=500)),
                ('Question2', models.CharField(default=None, max_length=500)),
                ('Response2', models.CharField(default=None, max_length=500)),
                ('Question3', models.CharField(default=None, max_length=500)),
                ('Response3', models.CharField(default=None, max_length=500)),
                ('Question4', models.CharField(default=None, max_length=500)),
                ('Response4', models.CharField(default=None, max_length=500)),
                ('Question5', models.CharField(default=None, max_length=500)),
                ('Response5', models.CharField(default=None, max_length=500)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Mercenaries',
            fields=[
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default=None, max_length=30)),
                ('last_name', models.CharField(default=None, max_length=30)),
                ('age', models.IntegerField(default=None)),
                ('cost', models.IntegerField(default=None)),
                ('number_of_actions', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=30)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default=None, max_length=30)),
                ('last_name', models.CharField(default=None, max_length=30)),
                ('autopsia', models.CharField(default=None, max_length=100)),
                ('gender', models.CharField(default=None, max_length=10)),
                ('age', models.IntegerField(default=None)),
                ('ethnic_group', models.CharField(default=None, max_length=15)),
                ('height', models.IntegerField(default=None)),
                ('hair_color', models.CharField(default=None, max_length=15)),
                ('eye_color', models.CharField(default=None, max_length=15)),
                ('profession', models.CharField(default=None, max_length=30)),
                ('resident', models.CharField(default=None, max_length=30)),
                ('income', models.IntegerField(default=None)),
                ('insurance_owner', models.BooleanField(default=None)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default=None, max_length=30)),
                ('last_name', models.CharField(default=None, max_length=30)),
                ('gender', models.CharField(default=None, max_length=10)),
                ('age', models.IntegerField(default=None)),
                ('ethnic_group', models.CharField(default=None, max_length=15)),
                ('height', models.IntegerField(default=None)),
                ('hair_color', models.CharField(default=None, max_length=15)),
                ('eye_color', models.CharField(default=None, max_length=15)),
                ('profession', models.CharField(default=None, max_length=30)),
                ('resident', models.CharField(default=None, max_length=30)),
                ('income', models.IntegerField(default=None)),
                ('danger_level', models.BooleanField(default=None)),
                ('corruption_cost', models.IntegerField(default=None)),
                ('bound_with_victim', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.victim')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('antecedent', models.CharField(default=None, max_length=100)),
                ('investigation', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.investigation')),
                ('suspect_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.suspect')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Prisoners',
            fields=[
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('guilty', models.BooleanField(default=None)),
                ('prime_value', models.IntegerField(default=None)),
                ('prisoner_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.suspect')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Killed',
            fields=[
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('guilty', models.BooleanField(default=None)),
                ('prime_value', models.IntegerField(default=None)),
                ('murdered_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.suspect')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='investigation',
            name='examination',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.suspect'),
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=None)),
                ('victim_insurance', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.victim')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Detective',
            fields=[
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('cover', models.CharField(default=None, max_length=30)),
                ('money', models.IntegerField(default=3000)),
                ('number_of_mercenaries', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.mercenaries')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Crime_location',
            fields=[
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('location', models.CharField(default=None, max_length=100)),
                ('crime', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.crime_detail')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='crime_detail',
            name='quest_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.quest'),
        ),
        migrations.AddField(
            model_name='crime_detail',
            name='victim_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.victim'),
        ),
        migrations.CreateModel(
            name='Clues',
            fields=[
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('clue', models.CharField(default=None, max_length=200)),
                ('crime_clues', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.crime_detail')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
