# Generated by Django 3.1.1 on 2020-09-25 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit_card',
            fields=[
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('credit_card_number', models.IntegerField(default=None)),
                ('credit_card_type', models.CharField(default=None, max_length=40)),
                ('card_owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.suspect')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('car_make', models.CharField(default=None, max_length=30)),
                ('car_model', models.CharField(default=None, max_length=30)),
                ('car_model_year', models.IntegerField(default=None)),
                ('car_VIN', models.IntegerField(default=None)),
                ('car_owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.suspect')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
