# Generated by Django 3.1 on 2020-09-06 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedent', models.CharField(max_length=100)),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.suspect')),
            ],
        ),
    ]
