# Generated by Django 3.1.1 on 2020-09-24 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crime_details',
            fields=[
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('estimated_date', models.IntegerField(default=None)),
                ('nature', models.CharField(default=None, max_length=30)),
                ('autopsia', models.CharField(default=None, max_length=100)),
                ('crime_quest', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.quest')),
                ('victim_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.victim')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='crime_detail',
            name='quest_id',
        ),
        migrations.RemoveField(
            model_name='crime_detail',
            name='victim_id',
        ),
        migrations.RemoveField(
            model_name='killed',
            name='guilty',
        ),
        migrations.RemoveField(
            model_name='prisoners',
            name='guilty',
        ),
        migrations.RemoveField(
            model_name='record',
            name='investigation',
        ),
        migrations.AlterField(
            model_name='detective',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='id',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Investigation',
        ),
        migrations.AlterField(
            model_name='clues',
            name='crime_clues',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.crime_details'),
        ),
        migrations.AlterField(
            model_name='crime_location',
            name='crime',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.crime_details'),
        ),
        migrations.DeleteModel(
            name='Crime_detail',
        ),
    ]
