# Generated by Django 3.1.1 on 2020-09-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200924_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercenaries',
            name='gender',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
