# Generated by Django 3.1.1 on 2020-09-14 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
