# Generated by Django 3.1.1 on 2020-09-25 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_car_credit_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_account',
            fields=[
                ('id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('credit_card_number', models.IntegerField(default=None)),
                ('credit_card_type', models.CharField(default=None, max_length=40)),
                ('IBAN', models.IntegerField(default=False)),
                ('card_owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.suspect')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Credit_card',
        ),
    ]
