# Generated by Django 3.1.1 on 2020-09-25 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200926_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='crime_details',
            name='location',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.DeleteModel(
            name='Crime_location',
        ),
    ]
