# Generated by Django 3.1.1 on 2020-09-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20200926_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspect',
            name='phone_number',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
