# Generated by Django 3.1.1 on 2020-09-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20200926_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_VIN',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
